# Site Settings
title: sienicki.dev
email: artur.sienicki@gmail.com
description: .NET Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sienicki.dev" # the base hostname & protocol for your site
google_analytics: "UA-144175258-1"

# User Settings
username: .NET Developer
user_description: Pięknie
disqus_username: asienickigithubio

# Social Media
# Remove the item if you don't need it
github_username: asienicki
facebook_username: facebook_username
twitter_username: ArturSienicki
instagram_username: instagram_username
linkedin_username: sienicki
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Start
    url: /
  - title: O mnie
    url: /about/
  - title: Kontakt
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
